[data]
train_split = 0.8
val_split = 0.2
batch_size = 64
shuffle = true

[model]
embedding_dim = 64
structure = "parallel"
dropout = 0.1
n_layers = 4

[optimizer]
learning_rate = 0.001
weight_decay = 1e-4

[training]
evaluation_interval = 1
n_epochs = 100